name: Run Tests

on:
  workflow_call:

jobs:
  test-python:
    runs-on: ubuntu-latest
    name: Python Unit Tests
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('platter-compiler-sveltejs/static/python/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        working-directory: platter-compiler-sveltejs/static/python
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run unittests
        run: |
          export PYTHONPATH="${GITHUB_WORKSPACE}/platter-compiler-sveltejs/static/python"
          cd platter-compiler-sveltejs/static/python
          python -m unittest discover -s tests -p "ga_*.py" -v

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: parser-test-results
          path: |
            platter-compiler-sveltejs/static/python/tests/syntax_programs/valid_test_results.txt
            platter-compiler-sveltejs/static/python/tests/syntax_programs/invalid_test_results.txt
            platter-compiler-sveltejs/static/python/tests/syntax_programs/test_results.txt
          if-no-files-found: ignore
